'''
Script to run moss against a directory of files.
'''

import subprocess
import os

#Run a command on the shell and return the results as a string.
def _run_command(command):
        p = subprocess.Popen(command,
                             stdout=subprocess.PIPE,
                             shell=True)
        return reduce(lambda x,y : x+y, iter(p.stdout.readline, b''))

'''
Sends a file to moss for examination.
Returns the result URL generated by moss.
USAGE: 
get_results('python', 'py', 'path/to/files')
'''
def get_results(language, extension, directory, base_file=None):
    if base_file is not None:
        cmd = 'perl moss -l %s -d %s/*/*.%s -b %s' % (language, directory, extension, base_file)
    else:
        cmd = 'perl moss -l %s -d %s/*/*.%s' % (language, directory, extension)
    results_url = _run_command(cmd).split('\n')[-2]
    return results_url
